version: "3.8"

services:
  # --- STORAGE ---
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  # --- CATALOG (Nessie) ---
  nessie:
    image: ghcr.io/projectnessie/nessie:latest
    container_name: nessie
    ports:
      - "${NESSIE_VERSION_CATALOG_PORT}:19120"
    environment:
      - QUARKUS_HTTP_PORT=19120
      - NESSIE_VERSION_STORE_TYPE=IN_MEMORY
      - NESSIE_CATALOG_DEFAULT_WAREHOUSE=nessie
      - NESSIE_CATALOG_WAREHOUSES_NESSIE_LOCATION=s3://airbnb-data/warehouse/
      - NESSIE_CATALOG_SERVICE_S3_DEFAULT_OPTIONS_ENDPOINT=http://minio:9000
      - NESSIE_CATALOG_SERVICE_S3_DEFAULT_OPTIONS_AUTH_TYPE=STATIC
      - NESSIE_CATALOG_SERVICE_S3_DEFAULT_OPTIONS_ACCESS_KEY=urn:nessie-secret:quarkus:s3.creds
      - S3_CREDS_NAME=${AWS_ACCESS_KEY_ID}
      - S3_CREDS_SECRET=${AWS_SECRET_ACCESS_KEY}
      - NESSIE_CATALOG_SERVICE_S3_DEFAULT_OPTIONS_REGION=${AWS_REGION:-us-east-1}
      - NESSIE_CATALOG_SERVICE_S3_DEFAULT_OPTIONS_PATH_STYLE_ACCESS=true
      - QUARKUS_S3_ENDPOINT_OVERRIDE=http://minio:9000
      - QUARKUS_S3_AWS_CREDENTIALS_TYPE=static
      - QUARKUS_S3_AWS_CREDENTIALS_STATIC_PROVIDER_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - QUARKUS_S3_AWS_CREDENTIALS_STATIC_PROVIDER_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - QUARKUS_S3_AWS_REGION=${AWS_REGION:-us-east-1}
      - QUARKUS_S3_PATH_STYLE_ACCESS=true
    env_file:
      - .env
    depends_on:
      - minio

  # --- METADATA DB ---
  dagster_db:
    image: postgres:13
    container_name: dagster_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - dagster_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # --- DAGSTER WEBSERVER ---
  dagster_webserver:
    build: ./dagster_project
    container_name: dagster_webserver
    volumes:
      - ./dagster_project:/opt/dagster/app
    entrypoint:
      [
        "dagster-webserver",
        "-h",
        "0.0.0.0",
        "-p",
        "3000",
        "-w",
        "workspace.yaml",
      ]
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - dagster_db
      # - nessie

  # --- DAGSTER DAEMON ---
  dagster_daemon:
    build: ./dagster_project
    container_name: dagster_daemon
    volumes:
      - ./dagster_project:/opt/dagster/app
    entrypoint: ["dagster-daemon", "run"]
    env_file:
      - .env
    depends_on:
      - dagster_db

  # --- ANALYTICS ---
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "${CLICKHOUSE_HTTP_PORT}:8123"
      - "${CLICKHOUSE_NATIVE_PORT}:9000"
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    profiles:
      - disabled

volumes:
  minio_data:
  dagster_db_data:
